# Generated by Django 4.2.2 on 2023-07-03 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=150)),
                ('abv', models.IntegerField(default=0)),
                ('brewery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beers', to='main_app.brewery')),
            ],
        ),
    ]
